apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "capi-kubeadm-control-plane.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "capi-kubeadm-control-plane.labels" . | nindent 4 }}
spec:
  selfSigned: {}