controllerManager:
  manager:
    image:
      repository: registry.k8s.io/cluster-api/kubeadm-control-plane-controller
      tag: v1.3.3
  replicas: 1
kubernetesClusterDomain: cluster.local
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
providerArgs:
  clusterTopology: false
  kubeadmBootstrapFormatIgnition: false